ExploratoryTestSystem/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from django.contrib import admin
admin.autodiscover()
# custom login admin
admin.site.login = login_required(admin.site.login)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ExploratoryTestSystem.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # index admin
    url(r'^admin/', include(admin.site.urls)),
    #custom login admin
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    # index page
    url(r'^$', 'exploratory.views.index'),
    # after login user will be redirected to this url
    url(r'^logged_in/$', 'exploratory.views.logged_in'),
    # using default django auth views with custom templates
    # url(r'^login/?next=/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    url(r'^sessions/$', 'exploratory.views.sessions'),
)

exploratory/urls.py
__author__ = 'Flavio'

from django.conf.urls import patterns, url

from exploratory import views

urlpatterns = patterns('',
    # url(r'^$', views.index, name='index'),
    # url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
)

charters/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models

# Create your models here.
class Charter(models.Model):
    charter_id = models.CharField(_('id'), max_length=20, primary_key=True)
    name = models.CharField(_('name'), max_length=100)
    objective = models.CharField(_('objective'), max_length=100)
    min_time = models.IntegerField(_('minimum'))
    max_time = models.IntegerField(_('maximum'))
    requeriments = models.TextField(_('requeriments'), null=True, blank=True)
    setup = models.TextField(_('setup'), null=True, blank=True)
    notes = models.TextField(_('notes'), null=True, blank=True)
    key_areas = models.TextField(_('key areas'), null=True, blank=True)
    issues = models.CharField(_('issues'), max_length=100, null=True, blank=True)
    important_notes = models.TextField(_('important notes'), null=True, blank=True)
    created_at = models.DateTimeField(_('created date'), auto_now_add=True, blank=True)
    modified_at = models.DateTimeField(_('modified date'), auto_now=True, blank=True)
    def __unicode__(self):
        return self.charter_id + ' - ' + self.name
    class Meta:
        verbose_name = _('Charter')

exploratory/models.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from charters.models import Charter
from django.db import models


# Create your models here.
class Comment(models.Model):
    description = models.TextField(_('description'))

    def __unicode__(self):
        return self.description

class Issue(models.Model):
    code_jira = models.CharField(_('CR'), max_length=20)
    name = models.CharField(_('name'), max_length=50)
    description = models.CharField(_('description'), max_length=100)
    tipo = models.CharField(_('type'), max_length=20)

    def __unicode__(self):
        return self.code_jira

class Label(models.Model):
    description = models.CharField(_('description'), max_length=50)

    def __unicode__(self):
        return self.description


class Product(models.Model):
    name = models.CharField(_('name'), max_length=50)
    project = models.CharField(_('project'), max_length=100)
    labels = models.ManyToManyField(Label)

    def __unicode__(self):
        return self.name + ' - ' + self.project

class Sessao(models.Model):
    tester = models.ForeignKey(User)
    duration = models.IntegerField(_('duration'))
    comments = models.TextField(_('comment'), null=True, blank=False)
    charter = models.ForeignKey(Charter)
    product = models.ForeignKey(Product)
    issues = models.ManyToManyField(Issue, null=True, blank=False)
    current_time = models.IntegerField(_('current time'), null=True, blank=False)
    def user_new_unicode(self):
        return self.username if self.get_full_name() == "" else self.get_full_name() + ' - ' + self.get_username()

    User.__unicode__ = user_new_unicode

    def __unicode__(self):
        return unicode(self.tester)

    class Meta:
        verbose_name = _('Session')
        verbose_name_plural = _('Sessions')

exploratory/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from exploratory.models import Sessao

# Create your views here.

# index view (just redirect to login page)
def index(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/logged_in')
    else:
        return HttpResponseRedirect('/accounts/login')

# this view will run after successfull login
@login_required
def logged_in(request):
    return render_to_response('logged_in.html',
                                context_instance=RequestContext(request))

# this view will show sessions
@login_required
def sessions(request, id):
    s = Sessao.objects.get(pk=id)
    return render_to_response('sessions.html', {
        'entry': s,
    }, context_instance=RequestContext(request))

exploratory/templates/base.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="utf-8">
{% block extrameta %}{% endblock %}

<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/bootstrap.css" />
{% block extrastyle %}{% endblock %}

</head>
<body class="{% block bodyclass %}{% endblock %}">
  <div class="container">
    {% block content %}
		{% endblock %}
    <footer></footer>
  </div>
  </body>
</html> 

exploratory/templates/logged_in.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-success">You are successfully logged in</div>
<a href='/logout'>Log out</a>
{% endblock %}

exploratory/templates/login.html
{% extends 'base.html' %}
{% block title %}Log in | Exploratory Test System{% endblock %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/signin.css" />
{% endblock %}
{% block content %}
  <form action="" class="form-signin" method="post">{% csrf_token %}
      <!--<h3 class="form-signin-heading text-center">Please log in</h3>-->
      <img class="form-signin-heading text-center" src="{{ STATIC_URL }}img/motorola_lenovo1.png" />
      {% if form.non_field_errors %}
          <div class="alert alert-danger">
            {{ form.non_field_errors|striptags }}
          </div>
      {% endif %}
      {% if not form.username.errors %}
        <input id="id_username" name="username" type="text" class="form-control" placeholder="CoreID" autofocus>
      {% else %}
        <div class="form-group has-error">
          {% for error in form.username.errors %}
            <label class="control-label" for="id_username">{{ error }}</label>
          {% endfor %}
          <input id="id_username" name="username" type="text" class="form-control" placeholder="CoreID" autofocus>
        </div>
      {% endif %}
      {% if not form.password.errors %}
        <input id="id_password" name="password" type="password" class="form-control" placeholder="Password" autofocus>
      {% else %}
        <div class="form-group has-error">
          {% for error in form.password.errors %}
            <label class="control-label" for="id_password">{{ error }}</label>
          {% endfor %}
          <input id="id_password" name="password" type="password" class="form-control" placeholder="Password">
        </div>
      {% endif %}
      
      <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    </form>
  </form>
{% endblock %}

exploratory/templates/logout.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-success">You are successfully logged out</div>
<a href='/login'>Log in</a>
{% endblock %}

exploratory/templates/sessions.html
{% extends "admin/base_site.html" %}

{% block title %} Details Sessions | Exploratory Test System{% endblock %}

{% load i18n admin_static admin_modify suit_tags admin_urls %}

{% block extrastyle %}
  {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}bootstrap/css/details.css" />
{% endblock %}

{% block extrajs %}
    {{ block.super }}
    <script src="/static/admin/js/admin/RelatedObjectLookups.js" type="text/javascript"></script>
    <script src="{% static 'suit/js/suit-form-confirm.js' %}"></script>
    <script type="text/javascript">
      confirmExitIfModified('sessao_form', '{% trans 'You have unsaved changes' %}.');
    </script>

    <script src="{{ STATIC_URL }}js/jquery.timer.js"></script>
    <script type="text/javascript">
        var sec = $('#current_time').val() == "None" ? 0 : $('#current_time').val()
        $('#id_current_time').timer({
            seconds: sec
        })
    </script>
    <script type="text/javascript">
        (function ($) {
          $('sessao_form :input[type!=button][type!=submit]:visible:enabled:first').focus();
        })(jQuery);
    </script>
{% endblock %}

{% block content %}
<h2 class="content-title">{% trans 'Details session' %}</h2>
<div id="content-main" class="inner-two-columns">
    {% if entry %}
    <form action="" id="sessao_form" enctype="multipart/form-data" class="form-horizontal" method="post">{% csrf_token %}
      <div class="inner-right-column">
        <div class="box save-box">
            <div class="submit-row clearfix">
                <!--<button class="btn btn-high btn-info" type="button">{% trans 'New Issues' %}</button>-->
                <button class="btn btn-high btn-info" name="_save" type="submit">{% trans 'Save' %}</button>
            </div>
        </div>

        <h4 class="italic-title">{% trans 'tools'|capfirst %}</h4>
        <ul class="box menu-box">
            <li><a href="/admin/exploratory/issue/add/?_to_field=id" onclick="return showAddAnotherPopup(this);" class="historylink"><i
                class="icon-time icon-alpha75"></i>{% trans "New Issues" %}</a>
            </li>
        </ul>

      </div>

    <div class="inner-center-column">
        <div class="tab-content tab-content-main">
            <fieldset class="module aligned first with-legend ">
                <h2 class="sub-header">{% trans 'Session Information' %}</h2>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Tester:</label>
                        </div>
                        <div class="controls">
                            <span>{{ entry.tester }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Product:</label>
                        </div>
                        <div class="controls">
                            <span>{{ entry.product }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Charter:</label>
                        </div>
                        <div class="controls">
                            <span>{{ entry.charter }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Duration:</label>
                        </div>
                        <div class="controls">
                            <span>{{ entry.duration }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row filter-current_time">
                    <div>
                        <div class="control-label">
                            <label>{% trans 'Remaining time' %}</label>
                        </div>
                        <div class="controls">
                            <span id="stopwatch"></span>
                            <input id="id_current_time" value="" disabled style="width:115px" />
                            <a href="#" onclick="$('#id_current_time').timer('resume')"><i class="icon-play"></i></a>
                            <a href="#" onclick="$('#id_current_time').timer('pause')"><i class="icon-pause"></i></a>
                            <input id="current_time" style="display:none" value="{{ entry.current_time }}" />
                        </div>
                    </div>
                </div>
            </fieldset>
            {% if charter %}
            <fieldset class="module aligned with-legend ">
                <h2 class="sub-header">{% trans 'Charter Information' %}</h2>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>{% trans 'Name' %}:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.name }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Objective:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.objective }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Requirements:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.requirements }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Setup:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.setup }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Notes:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.notes }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Key areas of concentration:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.key_areas }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Issues to be aware of:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.issues }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Important Notes:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.important_notes }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Maximum duration:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.max_time }}</span>
                        </div>
                    </div>
                </div>
                <div class="control-group form-row">
                    <div>
                        <div class="control-label">
                            <label>Minimum duration:</label>
                        </div>
                        <div class="controls">
                            <span>{{ charter.min_time }}</span>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset class="module aligned with-legend ">
                <h2 class="sub-header">{% trans 'Comments' %}</h2>
                <div class="control-group form-row field-comments">
                    <div>
                        <div class="control-label">
                            <label for="id_comments">{% trans 'Comments' %}</label>
                        </div>
                        <div class="controls">
                            <textarea id="id_comments" class="autosize">{{ charter.comments }}</textarea>
                        </div>
            </fieldset>
            {% endif %}
        </div>
    </div>
    </form>
    {% endif %}
</div>
{% endblock %}